# Generated by Django 5.1.15 on 2026-02-08 19:44

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_recalculate_durations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bmi",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "BMI",
                "verbose_name_plural": "BMI",
            },
        ),
        migrations.AlterModelOptions(
            name="headcircumference",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Head Circumference",
                "verbose_name_plural": "Head Circumference",
            },
        ),
        migrations.AlterModelOptions(
            name="height",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Height",
                "verbose_name_plural": "Height",
            },
        ),
        migrations.AlterModelOptions(
            name="weight",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Weight",
                "verbose_name_plural": "Weight",
            },
        ),
        migrations.CreateModel(
            name="MedicationSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "amount",
                    models.FloatField(blank=True, null=True, verbose_name="Amount"),
                ),
                (
                    "amount_unit",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Amount unit"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("interval", "Every X hours"),
                            ("weekly", "Specific days of week"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "schedule_time",
                    models.TimeField(
                        blank=True,
                        help_text="For daily/weekly schedules",
                        null=True,
                        verbose_name="Time of day",
                    ),
                ),
                (
                    "interval_hours",
                    models.FloatField(
                        blank=True,
                        help_text="For interval-based schedules (e.g., every 6 hours)",
                        null=True,
                        verbose_name="Interval (hours)",
                    ),
                ),
                ("monday", models.BooleanField(default=False, verbose_name="Monday")),
                ("tuesday", models.BooleanField(default=False, verbose_name="Tuesday")),
                (
                    "wednesday",
                    models.BooleanField(default=False, verbose_name="Wednesday"),
                ),
                (
                    "thursday",
                    models.BooleanField(default=False, verbose_name="Thursday"),
                ),
                ("friday", models.BooleanField(default=False, verbose_name="Friday")),
                (
                    "saturday",
                    models.BooleanField(default=False, verbose_name="Saturday"),
                ),
                ("sunday", models.BooleanField(default=False, verbose_name="Sunday")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_schedules",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication Schedule",
                "verbose_name_plural": "Medication Schedules",
                "ordering": ["name"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="Time"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "amount",
                    models.FloatField(blank=True, null=True, verbose_name="Amount"),
                ),
                (
                    "amount_unit",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Amount unit"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "tags",
                    core.models.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.Tagged",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "medication_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="log_entries",
                        to="core.medicationschedule",
                        verbose_name="Schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medications",
                "ordering": ["-time"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
    ]
