# Generated by Django 5.1.15 on 2026-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_bmi_options_alter_headcircumference_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="amount_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ml", "ml"),
                    ("mg", "mg"),
                    ("drops", "drops"),
                    ("IU", "IU"),
                    ("oz", "oz"),
                    ("tbsp", "tbsp"),
                    ("tsp", "tsp"),
                    ("puffs", "puffs"),
                ],
                max_length=50,
                verbose_name="Amount unit",
            ),
        ),
        migrations.AlterField(
            model_name="medicationschedule",
            name="amount_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ml", "ml"),
                    ("mg", "mg"),
                    ("drops", "drops"),
                    ("IU", "IU"),
                    ("oz", "oz"),
                    ("tbsp", "tbsp"),
                    ("tsp", "tsp"),
                    ("puffs", "puffs"),
                ],
                max_length=50,
                verbose_name="Amount unit",
            ),
        ),
    ]
