# Generated by Django 6.0.3 on 2026-04-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0038_alter_settings_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="unit_system",
            field=models.CharField(
                choices=[("metric", "Metric"), ("imperial", "Imperial")],
                default="metric",
                max_length=10,
                verbose_name="Unit System",
            ),
        ),
    ]
